"""initial schema

Revision ID: 0d603d6f9188
Revises: 
Create Date: 2025-04-17 12:15:06.409058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d603d6f9188'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('admins_remaining', sa.Integer(), nullable=False),
    sa.Column('members_remaining', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employee_device_tokens',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('purchased_saas',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('saas_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2083), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['owner'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('contract_id'),
    sa.UniqueConstraint('organization_id', 'url', name='uq_org_url')
    )
    op.create_table('employee_activities',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('purchased_saas_id', sa.Integer(), nullable=False),
    sa.Column('browser', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['purchased_saas_id'], ['purchased_saas.contract_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_activities')
    op.drop_table('purchased_saas')
    op.drop_table('employee_device_tokens')
    op.drop_table('employees')
    op.drop_table('organizations')
    # ### end Alembic commands ###
